### ISSUE TITLE
Add tag to render the react-refresh script

### ISSUE THREAD

**Issue by mixxorz** [MrBin99/django-vite#15] opened 2021-10-19 15:37 UTC
I wanted to raise another suggestion for django-vite.

When working with `@vitejs/plugin-react-refresh`, we need to include this script to enable HMR.

```html
<script type="module">
  import RefreshRuntime from 'http://localhost:3000/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
```

It would be fantastic if we could have a `{% vite_react_refresh_tag %}` or something similar to render this script. It would only render the script if `DEBUG` is true.

Thanks again for your wonderful work on this library.

Ref: https://vitejs.dev/guide/backend-integration.html

**Comment by MrBin99** [comment] 2021-10-19 15:54
Duplicate of #14

**Comment by burnedikt** [comment] 2023-05-25 13:22
I think this has been done with #53 but not released yet?

**Comment by burnedikt** [comment] 2023-05-25 21:23
> I think this has been done with #53 but not released yet?

Seems like it is released now in [version 2.1.0](https://github.com/MrBin99/django-vite/releases/tag/2.1.0) 🎉

**Closed as completed** 2023-11-26 18:31 UTC
Labels: duplicate, enhancement
